name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - unity_2017/Grizzly-Bear
        unityVersion:
          - 2019.3.14f1
        testMode:
          - playmode
          - editmode

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: webbertakken/unity-test-runner@v1.4
      id: tests
      with:
        projectPath: ${{ matrix.projectPath }}
        unityVersion: ${{ matrix.unityVersion }}
        testMode: ${{ matrix.testMode }}
        artifactsPath: ${{ matrix.testMode }}-artifacts
